cincoe:-display('Ingrese a: '),
	read(A),
	display('Ingrese b: '),
	read(B),
	display('Ingrese c: '),
	read(C),
        display('Ingrese d: '),
        read(D),
        display('Ingrese e: '),
        read(E),
        display('Ingrese f: '),
        read(F),
	Y is D*(3*C+E)-(F-(2*A))/((B+6)/(7*(4*(D-A))^2)),
	display(' El valor de Y es : '),
	display(Y).
